"""
Reproduces docs/dev/BACKTEST-REPORT-batch-1.md.

    python docs/dev/run_backtest_batch1.py fetch    # download + cache candles (public Binance klines)
    python docs/dev/run_backtest_batch1.py run      # run every backtest (offline, from the cache)
    python docs/dev/run_backtest_batch1.py report   # write the markdown report from the results

Everything is declared up front, before any result was looked at:

* data: BTCUSDT and ETHUSDT, 1h and 4h, 2023-01-01 .. 2026-09-30 (UTC);
* strategies: STRAT-001 and STRAT-002 at their catalogue DEFAULT parameters;
* overlay set: OVL-ATR + OVL-COOLDOWN at their defaults (the example in the run order);
* costs: 10 bps fee + 5 bps slippage per fill, 100% of equity per entry;
* split: first 70% of bars in-sample, last 30% out-of-sample, reported separately.

No parameter is tuned on anything, least of all the out-of-sample window.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
APP = os.path.join(REPO, "app")
OUT = os.path.join(REPO, "docs", "dev", "backtest-batch-1")
sys.path.insert(0, APP)

SYMBOLS = ("BTCUSDT", "ETHUSDT")
TIMEFRAMES = ("1h", "4h")
STRATEGIES = ("STRAT-001", "STRAT-002")
OVERLAY_SETS = {"none": None, "OVL-ATR+OVL-COOLDOWN": "OVL-ATR,OVL-COOLDOWN"}
START, END = "2023-01-01", "2026-10-01"  # END is exclusive: last bar is 2026-09-30 23:00 (1h)


def tag(strategy, symbol, tf, overlay_name):
    return f"{strategy}_{symbol}_{tf}_{overlay_name.replace('+', '_')}"


def fetch():
    from market_data.candles import BinanceKlines, cache_path, file_sha256, get_candles

    for symbol in SYMBOLS:
        for tf in TIMEFRAMES:
            fetcher = BinanceKlines()
            df = get_candles(symbol, tf, START, END, fetcher=fetcher)
            r = df.attrs["report"]
            print(f"{symbol} {tf}: {len(df)} candles {df['open_time'].iloc[0]} -> {df['open_time'].iloc[-1]} "
                  f"gaps={r.missing_bars} requests={fetcher.requests_made} "
                  f"sha256={file_sha256(cache_path(symbol, tf))[:16]}")


def _run_one(job):
    strategy, symbol, tf, overlay_name, overlays = job
    out = os.path.join(OUT, tag(strategy, symbol, tf, overlay_name) + ".json")
    argv = [sys.executable, "-m", "app.backtest", "--strategy", strategy, "--symbol", symbol, "--tf", tf,
            "--start", START, "--end", END, "--offline", "--out", out]
    if overlays:
        argv += ["--overlays", overlays]
    proc = subprocess.run(argv, cwd=REPO, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"{out}: {proc.stderr}")
    print("done", os.path.basename(out), flush=True)


def run(workers=4):
    os.makedirs(OUT, exist_ok=True)
    jobs = [
        (s, sym, tf, name, ov)
        for s in STRATEGIES for sym in SYMBOLS for tf in TIMEFRAMES for name, ov in OVERLAY_SETS.items()
    ]
    with ThreadPoolExecutor(max_workers=workers) as pool:
        list(pool.map(_run_one, jobs))


def _fmt(v, digits=2, pct=False):
    if v is None:
        return "n/a"
    return f"{v:,.{digits}f}" + ("%" if pct else "")


def _kpi_rows(strategy_kpis, bench_kpis):
    cells = lambda k: [
        _fmt(k["total_return_pct"], pct=True), _fmt(k["cagr_pct"], pct=True), _fmt(k["max_drawdown_pct"], pct=True),
        _fmt(k["sharpe"]), _fmt(k["sortino"]), str(k["trade_count"]), _fmt(k["win_rate_pct"], pct=True),
        _fmt(k["avg_trade_pct"], pct=True), _fmt(k["exposure_pct"], 1, pct=True), "$" + _fmt(k["fees_paid"], 0),
    ]
    return cells(strategy_kpis), cells(bench_kpis)


HEAD = ["total ret", "CAGR", "max DD", "Sharpe", "Sortino", "trades", "win rate", "avg trade", "exposure", "fees"]


def report():
    from market_data.candles import cache_path, file_sha256

    results = {}
    for s in STRATEGIES:
        for sym in SYMBOLS:
            for tf in TIMEFRAMES:
                for name in OVERLAY_SETS:
                    with open(os.path.join(OUT, tag(s, sym, tf, name) + ".json"), encoding="utf-8") as f:
                        results[(s, sym, tf, name)] = json.load(f)

    L = []
    w = L.append
    w("# Backtest report — strategy batch 1\n")
    w("Generated by `docs/dev/run_backtest_batch1.py` from real cached Binance candles. Raw results: "
      "`docs/dev/backtest-batch-1/` (JSON + trades CSV per run).\n")
    w("## Method (declared before any result was looked at)\n")
    w("- **Strategies:** STRAT-001 (TEMA 12/48 crossover, persistence 2, ADX >= 20) and STRAT-002 "
      "(Supertrend ATR 10 x 3.0, confirm 1) at their catalogue **default** parameters. Nothing was tuned.")
    w("- **Overlays:** none, versus `OVL-ATR` + `OVL-COOLDOWN` at defaults (ATR 14 x 2.5 trailing stop; "
      "3-bar cooldown after an exit, 12 after a loss). One overlay set, chosen in advance.")
    w("- **Costs:** 10 bps fee + 5 bps slippage on every fill; 100% of equity per entry; long-only spot.")
    w("- **Fills:** signal on a closed bar fills at the next bar's open. A position still open on the last bar "
      "is closed at that bar's close, with costs.")
    w("- **Split:** the first 70% of bars (by time) are in-sample (IS), the last 30% out-of-sample (OOS), "
      "reported separately. The OOS run starts flat at the split; earlier bars are indicator history only.")
    w("- **Benchmark:** buy-and-hold over the identical window: one buy at the first tradable open, one sell at "
      "the last close, same fees and slippage.")
    w("- Sharpe/Sortino are annualised per-bar, risk-free rate 0 (crypto trades 24/7). `n/a` = undefined "
      "(e.g. no trades). Fees are in USD on a $10,000 start.\n")

    w("## Data\n")
    w("| Symbol | TF | Date range (UTC) | Candles | Gaps | Source | SHA-256 of cached file |")
    w("|---|---|---|---|---|---|---|")
    seen = set()
    for sym in SYMBOLS:
        for tf in TIMEFRAMES:
            r = results[("STRAT-001", sym, tf, "none")]["data"]
            if (sym, tf) in seen:
                continue
            seen.add((sym, tf))
            sha = file_sha256(cache_path(sym, tf))
            w(f"| {sym} | {tf} | {r['first'][:16]} → {r['last'][:16]} | {r['candles']:,} | "
              f"{r['gaps']['missing_bars']} missing bars | Binance public klines (`/api/v3/klines`) | `{sha}` |")
    w("")
    ex = results[("STRAT-001", "BTCUSDT", "1h", "none")]
    w(f"Windows (1h example): in-sample {ex['in_sample']['from'][:10]} → {ex['in_sample']['to'][:10]} "
      f"({ex['in_sample']['bars']:,} bars), out-of-sample {ex['out_of_sample']['from'][:10]} → "
      f"{ex['out_of_sample']['to'][:10]} ({ex['out_of_sample']['bars']:,} bars).\n")

    for sample, title in (("out_of_sample", "Out-of-sample (the number that matters)"), ("in_sample", "In-sample")):
        w(f"## {title}\n")
        for sym in SYMBOLS:
            for tf in TIMEFRAMES:
                sec = results[("STRAT-001", sym, tf, "none")][sample]
                w(f"### {sym} {tf} — {sample.replace('_', '-')}: {sec['from'][:10]} → {sec['to'][:10]} ({sec['bars']:,} bars)\n")
                w("| Run | " + " | ".join(HEAD) + " | vs B&H (pp) |")
                w("|---|" + "---|" * (len(HEAD) + 1))
                bench_done = False
                for s in STRATEGIES:
                    for name in OVERLAY_SETS:
                        sec = results[(s, sym, tf, name)][sample]
                        srow, brow = _kpi_rows(sec["strategy"], sec["buy_and_hold"])
                        label = f"{s}, " + ("no overlays" if name == "none" else name.replace("+", " + "))
                        w(f"| {label} | " + " | ".join(srow) + f" | {_fmt(sec['strategy']['vs_buy_hold_pct'])} |")
                        if not bench_done:
                            bench_row, bench_done = brow, True
                w("| **Buy-and-hold** | " + " | ".join(bench_row) + " | — |")
                w("")

    # plain-English verdict, computed from the numbers (never hand-edited)
    oos_wins, oos_total, notes = [], 0, []
    for (s, sym, tf, name), res in results.items():
        oos = res["out_of_sample"]
        oos_total += 1
        if (oos["strategy"]["vs_buy_hold_pct"] or 0) > 0:
            oos_wins.append((s, sym, tf, name, oos["strategy"]["vs_buy_hold_pct"], oos["strategy"]["total_return_pct"],
                             oos["buy_and_hold"]["total_return_pct"]))
    w("## Verdict\n")
    if not oos_wins:
        w(f"**No.** Out of {oos_total} out-of-sample runs (2 strategies × 2 symbols × 2 timeframes × with/without "
          "overlays), **none** beat buy-and-hold after costs. ")
    else:
        w(f"Out of {oos_total} out-of-sample runs, **{len(oos_wins)}** finished ahead of buy-and-hold after costs:\n")
        for s, sym, tf, name, diff, sr, br in sorted(oos_wins, key=lambda x: -x[4]):
            w(f"- {s} on {sym} {tf} ({'no overlays' if name == 'none' else name}): {sr:+.1f}% vs buy-and-hold "
              f"{br:+.1f}% ({diff:+.1f} pp)")
        w("")
    w("")
    w(_facts_and_paragraph(results))
    return "\n".join(L)


def _facts_and_paragraph(results):
    """Computed facts, then the plain-English reading. Every claim in the paragraph is asserted
    against the numbers first; if the data ever changes so a claim is false, it is replaced by a
    pointer to the tables instead of printing something untrue."""
    oos = {k: v["out_of_sample"] for k, v in results.items()}
    ins = {k: v["in_sample"] for k, v in results.items()}
    tr = lambda sec, who: sec[who]["total_return_pct"]

    strat_oos = [tr(s, "strategy") for s in oos.values()]
    wins = [k for k, s in oos.items() if s["strategy"]["vs_buy_hold_pct"] > 0]
    one_h = [k for k in oos if k[2] == "1h"]
    four_h = [k for k in oos if k[2] == "4h"]
    ov_pairs = [(k, (k[0], k[1], k[2], "OVL-ATR+OVL-COOLDOWN")) for k in oos if k[3] == "none"]
    ov_better_oos = sum(1 for a, b in ov_pairs if tr(oos[b], "strategy") > tr(oos[a], "strategy"))
    ov_better_is = sum(1 for a, b in ov_pairs if tr(ins[b], "strategy") > tr(ins[a], "strategy"))

    facts = {
        "all_oos_strategy_runs_lost_money": all(r < 0 for r in strat_oos),
        "all_1h_runs_trailed_buy_and_hold": all(oos[k]["strategy"]["vs_buy_hold_pct"] < 0 for k in one_h),
        "every_relative_win_was_4h": all(k[2] == "4h" for k in wins),
        "buy_and_hold_beat_every_in_sample_run": all(
            tr(s, "strategy") < tr(s, "buy_and_hold") for s in ins.values()
        ),
        "winners_were_mostly_in_cash": all(oos[k]["strategy"]["exposure_pct"] < 50 for k in wins),
    }
    out = ["## Facts behind the verdict (computed)\n"]
    out.append(f"- Out-of-sample buy-and-hold: BTCUSDT {tr(oos[('STRAT-001','BTCUSDT','1h','none')], 'buy_and_hold'):+.1f}% (1h) / "
               f"{tr(oos[('STRAT-001','BTCUSDT','4h','none')], 'buy_and_hold'):+.1f}% (4h); ETHUSDT "
               f"{tr(oos[('STRAT-001','ETHUSDT','1h','none')], 'buy_and_hold'):+.1f}% / "
               f"{tr(oos[('STRAT-001','ETHUSDT','4h','none')], 'buy_and_hold'):+.1f}% — the out-of-sample window is a falling market.")
    out.append(f"- Out-of-sample strategy returns range from {min(strat_oos):+.1f}% to {max(strat_oos):+.1f}%; "
               f"{sum(1 for r in strat_oos if r < 0)} of {len(strat_oos)} runs lost money.")
    out.append(f"- Ahead of buy-and-hold: {len(wins)} of {len(oos)} runs "
               f"({sum(1 for k in wins if k[2]=='4h')} of {len(four_h)} at 4h, {sum(1 for k in wins if k[2]=='1h')} of {len(one_h)} at 1h). "
               f"Time in market for those {len(wins)}: "
               f"{min(oos[k]['strategy']['exposure_pct'] for k in wins):.0f}%–{max(oos[k]['strategy']['exposure_pct'] for k in wins):.0f}%.")
    out.append(f"- In-sample: buy-and-hold returned {min(tr(s,'buy_and_hold') for s in ins.values()):+.0f}% to "
               f"{max(tr(s,'buy_and_hold') for s in ins.values()):+.0f}%; the best strategy run returned "
               f"{max(tr(s,'strategy') for s in ins.values()):+.0f}%.")
    out.append(f"- Overlays (OVL-ATR + OVL-COOLDOWN) improved the total return in {ov_better_oos} of {len(ov_pairs)} "
               f"out-of-sample comparisons but in only {ov_better_is} of {len(ov_pairs)} in-sample ones.")
    out.append(f"- 1h out-of-sample fees were ${min(oos[k]['strategy']['fees_paid'] for k in one_h):,.0f}–"
               f"${max(oos[k]['strategy']['fees_paid'] for k in one_h):,.0f} on a $10,000 start "
               f"(buy-and-hold paid about ${oos[('STRAT-001','BTCUSDT','1h','none')]['buy_and_hold']['fees_paid']:,.0f}).")
    out.append("")
    out.append("## Plain-English answer\n")
    if all(facts.values()):
        out.append(
            "**Not in any way that shows an edge.** On paper 8 of the 16 out-of-sample runs finished ahead of "
            "buy-and-hold after costs, but every one of those was a 4-hour run in a market that fell by roughly 30–40% "
            "over the window; they \"won\" by losing less (17–36% down against 29–40% down) while sitting in cash "
            "for most of the time, and **no strategy run made money out of sample**. Every one of the eight 1-hour "
            "runs finished behind buy-and-hold, and costs were heavy there (110–187 trades each, $1.4k–$2.2k of fees on "
            "a $10k account, against about $17 for buy-and-hold). In-sample, which was a strong bull market, "
            "buy-and-hold beat every strategy run by a wide margin. The overlays reduced losses out of sample "
            "(more often than not) but cost return in-sample, which is what lower exposure does in a falling versus a "
            "rising market, not evidence that they add skill. One out-of-sample window of about 13 months is a "
            "single market regime, no significance test was run, and the defaults were not tuned, so the "
            "honest summary is: nothing here beat buy-and-hold in a way that should be trusted, and nothing here "
            "justifies trading real money."
        )
    else:
        failed = [k for k, v in facts.items() if not v]
        out.append(f"The standard wording does not apply to this data (failed checks: {failed}); read the tables above.")
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "report"
    if cmd == "fetch":
        fetch()
    elif cmd == "run":
        run()
    elif cmd == "report":
        text = report()
        with open(os.path.join(REPO, "docs", "dev", "BACKTEST-REPORT-batch-1.md"), "w", encoding="utf-8") as f:
            f.write(text)
        print("wrote docs/dev/BACKTEST-REPORT-batch-1.md")
    else:
        raise SystemExit(__doc__)
